[Session/9] Uni Test の追加
daichikuwa0618/flutter-weather-app pull request #22
Opened 2024-05-28 12:41 UTC by daichikuwa0618

## 課題

close #10 

## 対応箇所

- [x] [yumemi_weather](https://yumemi-inc.github.io/flutter-training-template/) API の呼び出しから Widget へ通知する部分までの [Unit tests](https://docs.flutter.dev/testing#unit-tests) を書く
- [ ] 余力があれば、JSON のエンコード・デコードの [Unit tests](https://docs.flutter.dev/testing#unit-tests) も書く
  - freezed + json の package の組み合わせて実装されているものなので、テストは不要と思い実装していません。

## 動作

動作に変更なし。

2024-05-28 12:47 UTC, daichikuwa0618 commented on test/util/create_container.dart
https://riverpod.dev/docs/essentials/testing#unit-tests のほぼコピペです。

2024-05-28 12:47 UTC, daichikuwa0618 commented on test/weather/weather_notifier_test.dart
> +            };
最初は `container.updateOverrides` で呼び出しタイミングによる動作を変えようとしていたのですが、

- override を更新するには `container.pump()` を呼び出す必要がある
- `WeatherNotifierProvider` も autoDispose されてしまって状態が破棄される
- やりたいテストができない

ということで、ローカルカウンタを用いた実装になりました。
`updateOverrides` 等の riverpod に用意されているものを用いた他のやり方があれば是非知りたいです。

2024-05-28 12:47 UTC, daichikuwa0618 commented on lib/infrastructure/weather_api.dart
> +YumemiWeather yumemiWeather(YumemiWeatherRef ref) {
テストで Mock を作るための薄いラッパーです。
Use Case から `yumemi_weather` package の依存を取り除くことがモチベーションではないので、そのまま `YumemiWeather` を返しています。

2024-05-29 21:09 UTC, rizumita requested changes

2024-05-29 21:09 UTC, rizumita commented on test/weather/use_case/get_weather_test.dart
> +        throwsA(const TypeMatcher<UnknownException>()),
以下の実装のisAというものが存在するので、多くの場合短いisAが利用されていると思います。

```dart
TypeMatcher<T> isA<T>() => TypeMatcher<T>();
```

2024-05-29 21:09 UTC, rizumita commented on test/weather/weather_notifier_test.dart
> +    test('成功 → 成功で状態が変わる', () {
一連の操作を行い、操作に従って変化した状態のリストを取得し、そのリストを検査すると分かりやすく記述することができます。

2024-05-29 21:09 UTC, rizumita commented on test/weather/weather_notifier_test.dart
> +      var count = 0;
Resultリストを作成して、popしていくことでcountを利用する必要が無くなり、overrideWith内で分岐する必要が無くなるので、テストの信頼性が上がります。テストではできる限り分岐は記述しないようにする方が良いです。

2024-06-03 07:18 UTC, daichikuwa0618 commented on test/weather/use_case/get_weather_test.dart
> +        throwsA(const TypeMatcher<UnknownException>()),
ありがとうございます。 8f28331f3b7506454506669ebbc42d16666ef7e0 で修正しました！

2024-06-03 07:19 UTC, daichikuwa0618 commented on test/weather/weather_notifier_test.dart
> +      var count = 0;
なるほど！参考になります！今後もこの方法でテストがより書きやすくなりそうです！
c0393005ec3a671d820b1f29c767ae9cbadb9965 で修正しました！

2024-06-03 07:20 UTC, daichikuwa0618 commented on test/weather/weather_notifier_test.dart
> +    test('成功 → 成功で状態が変わる', () {
テストケースを分けて無いので、setup / teardown が無いために、より実際に検証したい形でテストが書けていいですね。
ありがとうございます。

639f00370419173beee54530182c3528304505d6 で修正したのですが、ご指摘の内容をうまく反映できているでしょうか？

2024-06-03 07:21 UTC, daichikuwa0618 commented on test/weather/use_case/get_weather_test.dart
> +        throwsA(const TypeMatcher<UnknownException>()),
コミットのリンクをお送りしましたが、ネストも変わってて差分が非常に見にくいので、おそらく差分よりは直接追加されたファイルを見るほうがわかりやすいと思います。

2024-06-03 08:33 UTC, rizumita commented on test/weather/weather_notifier_test.dart
> +    test('成功 → 成功で状態が変わる', () {
Callable Objectを持つMockCallbackクラスを作成・利用してwhenで待ちかまえて、verifyInOrderで履歴を検査できると思います。

2024-06-07 03:02 UTC, daichikuwa0618 commented on test/weather/weather_notifier_test.dart
> +    test('成功 → 成功で状態が変わる', () {
baae759d42700f41b54776fd72cf52a86300b40a で修正しました！
ありがとうございます！

2024-06-07 03:03 UTC, daichikuwa0618 commented on test/weather/weather_notifier_test.dart
> +    test('成功 → 成功で状態が変わる', () {
前の実装だと例外っぽい実装に感じて微妙に思っていた

```dart
final initialState = container.read(weatherNotifierProvider);
expect(initialState, null); // 初期状態は null
```

このあたりも全て verifyInOrder に任せられて見通しが良くなった感じがします！

2024-06-11 02:39 UTC, rizumita approved these changes

2024-06-11 02:52 UTC, merged