[Session/10] Widget Tests
daichikuwa0618/flutter-weather-app pull request #23
Opened 2024-05-29 04:00 UTC by daichikuwa0618

## 課題

close #11 

## 対応箇所

- [ ] 次の [Widget tests](https://docs.flutter.dev/testing#widget-tests) を書く
	- [ ] 特定の条件で、天気予報画面に晴れの画像が表示されること
	- [ ] 特定の条件で、天気予報画面に曇りの画像が表示されること
	- [ ] 特定の条件で、天気予報画面に雨の画像が表示されること
	- [ ] 特定の条件で、天気予報画面に最高気温が表示されること
	- [ ] 特定の条件で、天気予報画面に最低気温が表示されること
	- [ ] 特定の条件で、天気予報画面にダイアログが表示され、特定のメッセージが表示されること
- [ ] 余裕があれば、他の [Widget tests](https://docs.flutter.dev/testing#widget-tests) も書く

## 動作

動作には変更なし。

2024-05-30 02:18 UTC, rizumita requested changes

2024-05-30 02:18 UTC, rizumita commented on test/weather/weather_screen_test.dart
> +      await tester.pump();
pumpは一定時間待つので、もしフレーム更新にそれ以上の時間がかかる場合には失敗します。
代わりにスケジュールされたフレーム更新が無くなるまで待つpumpAndSettleを利用すると良いです。

2024-05-30 02:18 UTC, rizumita commented on test/weather/weather_screen_test.dart
> +    testWidgets('天気情報が晴れ', (tester) async {
今回のPRで書き換える必要はありませんが、晴・曇・雨の正常系はParameterized Testingで記述することができます。
Flutterでは以下ように書きます。

```dart
final cases = [
  (WeatherCondition.sunny, 'sunny.svg'),
  …
];

for (final (condition, svg) in cases) {
  testWidgets(…);
}
```

2024-06-03 07:48 UTC, daichikuwa0618 commented on test/weather/weather_screen_test.dart
> +    testWidgets('天気情報が晴れ', (tester) async {
ありがとうございます！
https://github.com/daichikuwa0618/flutter-weather-app/pull/22#discussion_r1623894401 の修正が気持ち良すぎて、きれいにテストコードを書く楽しさを知ったので修正しました: cd5b0adabb70fe36a1a0241992930bada41aa540

(rizumita さん + Parametarized Testing といえば [rizumita/Kabura: Kabura is testing library for Swift](https://github.com/rizumita/Kabura) が思い出されます)

2024-06-03 07:50 UTC, daichikuwa0618 commented on test/weather/weather_screen_test.dart
> +      await tester.pump();
なるほど、結構まずかったですね。(ちゃんとドキュメント読んでなかった)
ありがとうございます！
0c9662e2b6dfdb2806ecce57a7e8cba0e973799d で修正しました。

実装見ると、こちらは内部で `while binding.hasScheduledFrame` の間 `pump` を呼び出し続ける形で実装されているんですね。納得です。

2024-06-05 08:37 UTC, rizumita approved these changes

2024-06-11 02:54 UTC, merged